# Screenshots preview/*.html (generated by validate.mjs) into preview/*.png for visual QA.
import glob, os, sys
from playwright.sync_api import sync_playwright
os.chdir(os.path.join(os.path.dirname(__file__), '..'))
with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={'width': 2400, 'height': 1000}, device_scale_factor=1)
    for f in sorted(glob.glob('preview/*.html')):
        if len(sys.argv) > 1 and not any(a in f for a in sys.argv[1:]): continue
        pg.goto('file://' + os.path.abspath(f)); pg.wait_for_timeout(300)
        pg.screenshot(path=f.replace('.html', '.png'), full_page=True)
        print('shot', f)
    b.close()
